on: [push, pull_request]
name: Check
defaults:
  run:
    shell: bash
jobs:
  check:
    name: Run Unit Tests
    runs-on: ['hyperenv', 'medium-eu-west-1']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Run tests
        run: |
          npm ci
          npm test
